---

- hosts: all
  gather_facts: no
  tasks:
  - name: Configure eth0 network interface 
    copy:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      content: |
        DEVICE=eth0
        BOOTPROTO=static
        ONBOOT=yes
        NETMASK=255.255.255.0
        GATEWAY=192.168.122.1
        DNS1=192.168.122.1

  - name: Delete ssh host keys
    shell: rm -rf /etc/ssh/ssh_host_*
 
  - name: Delete udev rules file
    shell: rm -rf /etc/udev/rules.d/70-*

  - name: Set hostname
    shell: hostnamectl set-hostname localhost.localdomain

  - name: Subscribe to RHN
    redhat_subscription:
      state: present
      activationkey: 
      org_id: 
      pool_ids: 
      
  - name: Enable repos
    shell: subscription-manager repos --disable "*" --enable rhel-7-server-rpms
  
  - name: Yum update
    yum:
      name: '*'
      state: latest
